services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: varsemp
    ports:
      - "5432:5432"
    networks:
      - employee-net
    volumes:
      - pg-data:/var/lib/postgresql/data
#--------------------Authentication---------------
  authentication:
    image: tummaadityareddy/authentication:${IMAGE_VERSION}
    container_name: authentication
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/varsemp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - employee-net
#--------------------Employee---------------
  employee:
    image: tummaadityareddy/employee:${IMAGE_VERSION}
    container_name: employee
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/varsemp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - employee-net
#--------------------ApiGateway--------------
  apigateway:
    image: tummaadityareddy/apigateway:${IMAGE_VERSION}
    container_name: apigateway
    ports:
      - "8080:8080"
    depends_on:
      - authentication
      - employee
    environment:
      authentication: http://authentication:8081
      employee: http://employee:8082
    networks:
      - employee-net
networks:
  employee-net:

volumes:
  pg-data: